expression  -> term ;
term        -> factor ( "+" factor )* ;
factor      -> unary ( "*" unary )*
unary       -> "!" unary
             | primary ;
primary     -> ( "1" | "0" )
             | identifier
             | "(" expression ")" ;

identifier  -> STRING ( STRING | NUMBER )* ;

NUMBER      -> digit+ ;
STRING      -> character+ ;

character   -> "a" - "z" | "A" - "Z" | "_" ;
digit       -> "0" - "9" ;
operator    -> | "+" | "*" | "!" ;


Term        +
Factor      *
Unary       !
